apiVersion: v1
kind: Pod
metadata:
  name: root-os3
spec:
  containers:
  - command: ["/bin/sleep","1d"]
    image: alpine:3.14
    name: root-os3
    securityContext:
      privileged: true
  hostPID: true


